name: Build darkGram APK

on:
  push:
    branches: [ master ]
  workflow_dispatch: # Позволяет запускать сборку кнопкой вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Чтобы подтянулись все части Телеграма

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # Мы собираем Debug версию, так как для Release нужны ключи подписи
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: darkGram-debug
          path: TMessagesProj/build/outputs/apk/debug/*.apk
